Save_Our_Ocean/Models/Voluntario.cs
using System.ComponentModel.DataAnnotations;

namespace Save_Our_Ocean.Models
{
    public class Voluntario
    {


        [Key]
        public int Id { get; set; }

        [Required]
        public string Nome { get; set; }

        [Required]

        public string Email { get; set; }

        [Required]
        public string Senha { get; set; }

        [Required]

        public string sexo { get; set; }


        public ICollection<Area> Area { get; set; }

    }
}

Save_Our_Ocean/Controllers/AreaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Save_Our_Ocean.Data;
using Save_Our_Ocean.DTOs;
using Save_Our_Ocean.Models;

namespace Save_Our_Ocean.Controllers
{
    public class AreaController : Controller
    {


        private readonly ILogger<AreaController> _logger;



        private readonly DataContext _dataContext;


        public AreaController(ILogger<AreaController> logger, DataContext dataContext)
        {
            _dataContext = dataContext;
            _logger = logger;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CadastrarArea()
        {

            var id = HttpContext.Session.GetInt32("_Id");
            var idVoluntario = _dataContext.Voluntario.Find(id);
            ViewBag.IdVoluntario = idVoluntario.Id;

            return View();
        }

        public IActionResult CadastroArea(CadastroAreaDTO request, int idVoluntario)
        {
            var vef = _dataContext.Area.FirstOrDefault(x => x.Cep == request.Cep);

            if (vef != null)
            {
                return BadRequest("Area ja Cadastrada");
            }

            Area area = new Area
            {
                Cep = request.Cep,
                TipoPoluicao = request.TipoPoluicao,
                Descricao = request.Descricao,
                VoluntarioId = idVoluntario,
            };


            _dataContext.Add(area);
            _dataContext.SaveChanges();

            return View("~/Views/Voluntario/Home.cshtml");
        }

        public async Task<IActionResult> ListaDeAreaLimpas()
        {
            // Recupere os dados das tabelas de área e eventos
            var areas = await _dataContext.Area.ToListAsync();



            return View(areas);
        }


    }
}

Save_Our_Ocean/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Save_Our_Ocean.Models;
using System.Diagnostics;

namespace Save_Our_Ocean.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Save_Our_Ocean/Controllers/VoluntarioController.cs
using Microsoft.AspNetCore.Mvc;
using Save_Our_Ocean.Data;
using Save_Our_Ocean.DTOs;
using Save_Our_Ocean.Models;

namespace Save_Our_Ocean.Controllers
{
    public class VoluntarioController : Controller
    {


        private readonly ILogger<VoluntarioController> _logger;


        private readonly DataContext _dataContext;


        public VoluntarioController(ILogger<VoluntarioController> logger, DataContext dataContext)
        {
            _dataContext = dataContext;
            _logger = logger;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoginPage()
        {
            return View();
        }

        public IActionResult Home()
        {
            return View();
        }


        public IActionResult LogarVoluntario(LoginVoluntarioDTO request)
        {

            var voluntario = _dataContext.Voluntario.FirstOrDefault(x => x.Email == request.Email);

            if (voluntario == null)
            {
                return BadRequest("Email invalido");
            }

            if (voluntario.Senha != request.Senha)
            {
                return BadRequest("Senha Invalida");
            }


            HttpContext.Session.SetInt32("_Id", voluntario.Id);

            return RedirectToAction("Home");
        }

        public IActionResult CadastroConta()
        {
            return View();
        }

        public IActionResult CadastrarConta(CadastrarVoluntarioDTO request)
        {
            var voluntario = _dataContext.Voluntario.FirstOrDefault(x => x.Email == request.Email);

            if (voluntario != null)
            {
                return BadRequest("Voluntario ja foi cadastrado com esse email se atente");
            }

            Voluntario newVoluntario = new Voluntario
            {
                Nome = request.Nome,
                Email = request.Email,
                Senha = request.Senha,
                sexo = request.Sexo,
            };

            _dataContext.Add(newVoluntario);
            _dataContext.SaveChanges();

            return RedirectToAction("LoginPage");
        }


       
    }
}

Save_Our_Ocean/Views/Voluntario/CadastroConta.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcoOcean</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Inscreening.styles.css" asp-append-version="true" />
    <link href="~/css/Cadastro.css" rel="stylesheet" type="text/css" />
    <style>
        /* Seletor para o campo de data */
        input[type="date"] {
            /* Define a cor do texto */
            color: #808080; /* Aqui você pode especificar a cor que deseja, por exemplo, branco (#fff) */
            /* Define outras propriedades, como fonte, tamanho, etc., se desejar */
        }
    </style>
</head>
<body>


    <form asp-controller="Voluntario" asp-action="CadastrarConta" method="post">
        <div class="agrupamento">
            <h1 class="titulo">Cadatro de Voluntario</h1>
        </div>

        <div class="agrupamento-input">

            <input class="inputs" name="Nome" type="text" id="exampleInputPassword1" required placeholder="Nome">
            <br />

            <input class="inputs" name="Email" type="text" id="exampleInputPassword1" required placeholder="Email">

            <br />
            <input class="inputs" name="Sexo" type="text" id="exampleInputPassword1" required placeholder="Sexo">

            <br />
            <input class="inputs" name="Senha" type="text" id="exampleInputPassword1" required placeholder="Senha">

        </div>


        <div class="agrupamento-links">
            <button type="submit" class="btn btn-primary">Registrar</button>
            <br />
            <br />
        </div>

    </form>
</body>
</html>

Save_Our_Ocean/Views/Voluntario/Home.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcoOcean</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/PaginaInicial.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Tabela.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <br />
    <br />
    <br />
    <br />
    <br />
    <div class="logo">

        <a class="btn" asp-area="" asp-controller="Home" asp-action="Index">Voltar</a>
    </div>
    <h1 class="titulo">Selecione a area de acesso</h1>

    <div class="agrupamento">
        <button class="item">
            <a class="button-text" asp-controller="Area" asp-action="CadastrarArea">Cadastrar Area</a>
        </button>
        <br />
        <button class="item">
            <a class="button-text" asp-controller="Area" asp-action="ListaDeAreaLimpas">Lista De Area Limpas</a>
        </button>
        <br />
  
    </div>
</body>
</html>

Save_Our_Ocean/Views/Voluntario/LoginPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcoOcean</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Inscreening.styles.css" asp-append-version="true" />
    <link href="~/css/Login.css" rel="stylesheet" type="text/css" />
    <style>
        .imagem {
            width: 150px;
        }
    </style>
</head>
<body>


    <form asp-controller="Voluntario" asp-action="LogarVoluntario" method="post">

        <div class="agrupamento">
            <h1 class="titulo">Save Our Ocean</h1>

        </div>

        <br />
        <br />


        <div class="agrupamento-input">

            <input class="inputs" name="Email" type="text" class="form-control" id="exampleInputPassword1" required placeholder="Email">

            <br />
            <input class="inputs" name="Senha" type="text" class="form-control" id="exampleInputPassword1" required placeholder="Password">

        </div>

        <br />
        <br />

        <div class="agrupamento-links">
            <button type="submit" class="btn btn-primary">Submit</button>
            <br />
            <a class="criar" asp-area="" asp-controller="Voluntario" asp-action="CadastroConta">Criar Conta</a>
            <br />
            <br />
        </div>


    </form>
</body>
</html>